### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by jkowalleck**
First release.

## Responsibilities
- Provide a yarn plugin that generates CycloneDX SBOM for current workspace
- Provide a CLI wrapper got said plugin  

## Capabilities
- Supports yarn3 and yarn4
- Can output in XML and JSON format, CycloneDX v1.2 - v1.6 spec
- Can omit dev dependencies

----

:building_construction:  GOALS
- [x] have the license situation clarified -- #104
- [x] have _all_ implementation done
    see https://github.com/CycloneDX/cyclonedx-node-yarn/milestone/1
- [x] have integration tests with real yarn setups
- [x] have have CI/CT ready
- [x] have dependabot working
- [x] have release action in place  
  see #103  
  have a pre-release published to github, that
  - has the resulting package as an asset
  - has the resulting plugin-script as an asset 
  - has the 3rd party notice as an asset
- [x] have license headers in all files
- [x] have docs finalized
- [x] have scripts for build, lint, cs-fix, etc ... 
- [ ] squash/fixup all commits in this PR to one commit with a proper commit message that explains capabilities and responsibilities.
  This will be done on merge - quash merge  
- :exclamation: after merge: https://github.com/CycloneDX/cyclonedx-node-yarn/issues/27

### CODE REVIEW

**Comment by jkowalleck** [comment]
Ready for review.
All contributions and comments are welcome.

**Comment by jkowalleck** [comment]
@AugustusKling @jayshindeinfor @jdalton @rart, 
I want to inform you, that this tool/plugin is fresh out of beta. The current release candidate is planned to be released end of June.

In the meantime, public testing is appreciated.
An experience report, a code review, and any feedback is more than welcome.

If you want to give it a try, the installation instructions and usage descriptions are up-to-date in the [README file](https://github.com/CycloneDX/cyclonedx-node-yarn?tab=readme-ov-file#readme).

Thank you all for your contribution.

**Comment by jkowalleck** [comment]
re: https://github.com/CycloneDX/cyclonedx-node-yarn/pull/6#issuecomment-2179384678

> Using the plugin using the YARN_PLUGINS environment variable should be mentioned in the readme because this allows to use the plugin without interfering with the project for which the SBOM is generated. It's an alternative to `yarn dlx` which works also in isolated environments.

The `yarn dlx` creates an isolated environment on the fly. That's why I've put it on the top of the lists — it is probably the least inversive method of running this plugin.
Advanced users of yarn know about the YARN_PLUGINS env var and how to use it; I'd rather not document it, so the new users are not confused, and so the usage is clear and simple.


> The default of emitting the JSON SBOM to the standard output is not really useful in combination with `yarn dlx` as it also writes logs to the standard output. The readme should mention the invocation using `yarn dlx --quiet`.

Thank you so much for bringing this up. :+1: 
Added this to the docs! 

> When attempting to generate the SBOM and a package.json contains for example "version": "1.0-dev" it now crashes in a function called Object.fixVersionField. This concerns me as I would not expect the SBOM generation to adjust version numbers and instead just take them verbatim.

Thanks for testing this. :+1: 
Converted this remark to #133.

> The SBOM files do no longer identify package instances by their locator hash but use pretty printed identifiers of package names and version numbers instead (value in the bom-ref fields). This is okay as long as the hash is appended for virtual packages. Since I'm pretty sure the hash is clipped to the first 5 characters you may see duplicated identifiers with really low probability.


Internally, the components are not identified per <name>@<version>, but by yarn's own `descriptorHash`.
The CycloneDX library asserts that `bom-ref`s are unique per document, and makes them unique if needed. 
So there is no need to add/append any hashes, or is there? If there was, i'd probably register and use a CyclieDX property to store yarn's `locatorHash` in the SBOM.
@AugustusKling, please advice.

**Comment by AugustusKling** [comment]
> re: [#6 (comment)](https://github.com/CycloneDX/cyclonedx-node-yarn/pull/6#issuecomment-2179384678)
> [...]
> > The SBOM files do no longer identify package instances by their locator hash but use pretty printed identifiers of package names and version numbers instead (value in the bom-ref fields). This is okay as long as the hash is appended for virtual packages. Since I'm pretty sure the hash is clipped to the first 5 characters you may see duplicated identifiers with really low probability.
> 
> Internally, the components are not identified per @, but by yarn's own `descriptorHash`. The CycloneDX library asserts that `bom-ref`s are unique per document, and makes them unique if needed. So there is no need to add/append any hashes, or is there? If there was, i'd probably register and use a CyclieDX property to store yarn's `locatorHash` in the SBOM. @AugustusKling, please advice.

Usually the "descriptor" is the package plus version range as found in a package.json. The "locator" is the package plus a fixed version as in after Yarn decided which version to pick given a version range.

I think the value in `Package.locatorHash`, not `descriptorHash`, is even unique when virtual packages are required (see https://yarnpkg.com/advanced/lexicon#virtual-package). Such package instances need to be created in certain cases when a package occurs multiple times in the dependency tree but would resolve its own dependencies to different versions for different instantiations. For example different peer dependencies are provided in the different branches of the transitive dependency tree.

If the Cyclone DX library ensures `bom-ref` properties are unique across all components we could be sure that all produced SBOM files are okay.

My original code created the `CDX.Models.Component` instances first and thereafter added the dependencies for each component. In case the current code still follows the same approach, then I don't understand how the Cyclone DX library could make the `bom-ref` unique while still retriving the correct dependencies by a `descriptorHash`. Doing the same with `locatorHash`  should be correct, though.

Sadly, I don't have the time these days to read your code in detail but it might be enough to simply get the dependencies by `locatorHash` instead of `descriptorHash`. There is no need to include the `locatorHash` in the SBOM file as it's just in implementation detail of Yarn. What you should guarantee is that each `locatorHash` value maps to exactly 1 `bom-ref` value but it does not matter which value is used for the `bom-ref` in the generated SBOM.

**Comment by jkowalleck** [comment]
> Such package instances need to be created in certain cases when a package occurs multiple times in the dependency tree but would resolve its own dependencies to different versions for different instantiations. For example different peer dependencies are provided in the different branches of the transitive dependency tree.

would you be able to craft a test bed for testing this?
I will try and might come back in a separate pull request.

Regarding `locatorHash` versus `descriptorHash` -- in all test beds I tried, I was able to reproducibly craft resulted based on `descriptorHash`, but not based on `locatorHash`. this is why ... 


If all this only about a unique `bom-ref`, rest assured that the library takes care of it. 
It uses a reversible discriminator mechanism right before normalizing/serializing the data models.

**Pull request merged**
